// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mixczbogwrppacvxrsma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1peGN6Ym9nd3JwcGFjdnhyc21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTUzMzIsImV4cCI6MjA2MDY5MTMzMn0.3NclEXlF6uu2sIMGZjN41y79hgaXeldJdzqhHBFGc7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);